version: '3'

services:
  nginx1:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./site:/var/www/html

  nginx2:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./site:/var/www/html

  php1:
    build:
      context: ./php
    volumes:
      - ./site:/var/www/html
    depends_on:
      - mysql

  php2:
    build:
      context: ./php
    volumes:
      - ./site:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD:password
